<a href="{{link}}" target="_blank">
    <img src="{{picture}}" alt="">
    <div class="opt_wrapper"></div>
    <div class="info">
        <div class="info-icon">$</div>
        <div class="info-category">{{category}}</div>
        <div class="info-title">
            <span>{{title}}</span>
        </div>
        <div class="info-author">{{author}}</div>
        <div class="info-timestamp">{{timestamp}}</div>
    </div>
</a>
