<div class="content-top">
    <a class="logo" id="logo" target="_blank">
        <div class="preload" data-source="image/logo.svg"></div>
    </a>

    <div class="social-wrapper">
        <div class="facebook share" id="top-share-facebook">f</div>
        <div class="twitter share" id="top-share-twitter">t</div>
        <div class="pinterest share" id="top-share-pinterest">p</div>
    </div>
</div>
